.TH mattext 1 "26 September 2015"
.SH NAME
mattext \- Simple matrix\-style pager.

.SH USAGE
.B mattext
.RB [\| \-d
.IR delay \|]
.RB [\| \-l
.IR length \|]
.RB [\| \-n \|]
.RB [\| \-i \|]
.RB [\| \-b
.IR lines \|]
.RB [\| \-B \|]
.RB [\| \-N \|]
.RB [\| \-C \|]
.RB [\| \-V \|]
.RB [\| \-e \|]
.RB [\| \-a
.IR name \|]
.RI [\| file \ .\|.\|. \| ]

.SH DESCRIPTION
.PP
Mattext shows text with matrix\-style rain\-of\-symbols animation during page changes.

.SH COMMANDS
.TP
.B q\fR or \fBctrl + D
Exit program.
.TP
.B f\fR or \fBj\fR or \fBspace\fR or \fBPgDown\fR or \fBDown
Show next page.
.TP
.B b\fR or \fBk\fR or \fBPgUp\fR or \fBUp
Show next page.

.SH OPTIONS
.TP
.B \-d\ \fIdelay\fR,\ \fB\-\-delay\ \fIdelay
Delay between screen redraws, in ms, default 60.
.TP
.B \-l\ \fIlength\fR,\ \fB\-\-rand-len\ \fIlength
Maximum length of random symbols columns.
.TP
.B \-n\fR,\ \fB\-\-non\-interact
Do not wait for user input before showing next page.
.TP
.B \-i\fR,\ \fB\-\-infinite
At the end of file start reading it from the beginning.
.TP
.B \-b\ \fIlines\fR,\ \fB\-\-block\-lines\ \fIlines
Block until at least specified number of lines is read, default 1.
.TP
.B \-B\fR,\ \fB\-\-block\-page
Block until full page is read.
.TP
.B \-N\fR,\ \fB\-\-no\-color
Do not colorize output.
.TP
.B \-C\fR,\ \fB\-\-center\-horiz
Center text horizontally.
.TP
.B \-L\fR,\ \fB\-\-center\-horiz\-longest
Center text horizontally by longest string.
.TP
.B \-v\fR,\ \fB\-\-center\-vert
Center text vertically.
.TP
.B \-e\fR,\ \fB\-\-without\-japanese
Do not use Japanese symbols.
.TP
.B \-a\ \fIname\fR,\ \fB\-\-animation\ \fIname
Animation for switching pages. Available animations are matrix, reverse_matrix, none.
.TP
.B \-\-animation\-next
Animation for showing next page.
.TP
.B \-\-animation\-prev
Animation for showing prev page.

.SH EXAMPLES
.TP
.B mattext file
Show file one page at a time, and exit at the end.
.TP
.B mattext -ni file
Show file until exit key is pressed. When end is reached mattext starts reading it from the beginning.
.TP
.B tail -f file | mattext -n
Show file, waiting for at least one new line added to it before redrawing screen.
.TP
.B echo | mattext -ni -b 0
Show animation until quit command key is pressed, similar to cmatrix.
.TP
.B mattext -niLv dir/*
Show all files from directory dir, centrating text horizontally by longest line and vertically, until exit key is pressed. When mattext reaches the end of the last file it starts reading the first file. This mode can be useful for showing off your ascii art collection.

.SH TROUBLESHOOTING
.TP
If you see white squares instead of some symbols, there can be 3 options:
.TP
.B 1.\fR Your terminal does not support unicode - you can use another terminal or \fB\-\-without\-japanese\fR option;
.TP
.B 2.\fR You do not have any Japanese font - run \fBfc\-list :lang=ja\fR and if this command shows nothing, install some. For example, Droid;
.TP
.B 3.\fR Your terminal can't find this font - add it to the terminal's fonts list. For example, urxvt config should look like \fBURxvt.font: xft:Liberation Mono:size=11, xft:Droid Sans Fallback:size=11\fR;

.SH AUTHOR
Denis Tikhomirov (dvtikhomirov@gmail.com)
