.TH mattext 1 "26 September 2015"
.SH NAME
mattext \- Simple matrix\-style pager.

.SH USAGE
.B mattext
.RB [\| \-d
.IR delay \|]
.RB [\| \-l
.IR length \|]
.RB [\| \-n \|]
.RB [\| \-i \|]
.RB [\| \-b
.IR lines \|]
.RB [\| \-B \|]
.RB [\| \-c \|]
.RB [\| \-C \|]
.RB [\| \-V \|]
.RB [\| \-e \|]
.RI [\| file \ .\|.\|. \| ]

.SH DESCRIPTION
.PP
Mattext shows text with matrix\-style rain\-of\-symbols animation during page changes.

.SH COMMANDS
.TP
.B q\fR or \fBQ\fR or \fBctrl + D
Exit program.
.TP
.B any other key
Show next page.

.SH OPTIONS
.TP
.B \-d\ \fIdelay\fR,\ \fB\-\-delay\ \fIdelay
Delay between screen redraws, in ms, default 80.
.TP
.B \-l\ \fIlength\fR,\ \fB\-\-rand-len\ \fIlength
Maximum length of random symbols columns.
.TP
.B \-n\fR,\ \fB\-\-non\-interact
Do not wait for user input before showing next page.
.TP
.B \-i\fR,\ \fB\-\-infinite
At the end of file start reading it from the beginning.
.TP
.B \-b\ \fIlines\fR,\ \fB\-\-block\-lines\ \fIlines
Block until at least specified number of lines is read, default 1.
.TP
.B \-B\fR,\ \fB\-\-block\-page
Block until full page is read.
.TP
.B \-c\fR,\ \fB\-\-colorize
Colorize output.
.TP
.B \-C\fR,\ \fB\-\-center\-horiz
Center text horizontally.
.TP
.B \-L\fR,\ \fB\-\-center\-horiz\-longest
Center text horizontally by longest string.
.TP
.B \-v\fR,\ \fB\-\-center\-vert
Center text vertically.
.TP
.B \-e\fR,\ \fB\-\-without\-japanese
Do not use Japanese symbols.

.SH EXAMPLES
.TP
.B mattext -c file
Show file, colorizing console, one page at a time, and exit at the end.
.TP
.B mattext -cni file
Show file, colorizing console, until exit key is pressed. When end is reached mattext starts reading it from the beginning.
.TP
.B tail -f file | mattext -n
Show file, waiting for at least one new line added to it before redrawing screen.
.TP
.B echo | mattext -ni -b 0
Show animation until quit command key is pressed, similar to cmatrix.
.TP
.B mattext -niLv dir/*
Show all files from directory dir, centrating text horizontally by longest line and vertically, until exit key is pressed. When mattext reaches the end of the last file it starts reading the first file. This mode can be useful for showing off your ascii art collection.

.SH AUTHOR
Denis Tikhomirov (dvtikhomirov@gmail.com)
